// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjBIWYVP49P4zPOorrY1U8JET6b3C-Bv8',
    appId: '1:316040241394:web:3dcf0eea5894ee9370706b',
    messagingSenderId: '316040241394',
    projectId: 'appopreturn-prod',
    authDomain: 'appopreturn-prod.firebaseapp.com',
    storageBucket: 'appopreturn-prod.firebasestorage.app',
    measurementId: 'G-H31K6R2F3J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDm5G7ACaOEj7yvAMZr_F7EHrN0AUdaq4',
    appId: '1:316040241394:android:1f8a6a8dc5c3bc3470706b',
    messagingSenderId: '316040241394',
    projectId: 'appopreturn-prod',
    storageBucket: 'appopreturn-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6G2O6FpDDkajVvtH2hWVqmaGX3LI6Km4',
    appId: '1:316040241394:ios:64c238ca08ed8db570706b',
    messagingSenderId: '316040241394',
    projectId: 'appopreturn-prod',
    storageBucket: 'appopreturn-prod.firebasestorage.app',
    iosBundleId: 'com.autheet.appopreturn',
  );

}